package RCLTestScript;

import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Cookie;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class Handlingcookies {

	public static void main(String[] args) {
	WebDriverManager.chromedriver().setup();
	WebDriver driver=new ChromeDriver();
	driver.manage().timeouts().implicitlyWait(100, TimeUnit.SECONDS);
	driver.get("https://www.easemytrip.com/");
	//driver.get("https://www.redbus.in/");
	
	driver.manage().window().maximize();
	
	
	//Cookies-Cookies are temprory files which are generated by the Browser when you visiting some websites.
	
	//How to capture cookies from browser
	
	     Set<Cookie>   cookies=driver.manage().getCookies();
	     
	     System.out.println("Size of cookies:"+cookies.size());//25
	     
	     //How to print cookies from browser
	     
	     for(     Cookie   cookie   :cookies)
	     {
	    	 
	    	 System.out.println(cookie.getName()+"   :  "+cookie.getValue());
	    	 
	     }
	     
	     //How to add cookies to the browser
	     
	     Cookie cookieobj=new Cookie("Selenium123", "Abcd123456789");
	     driver.manage().addCookie(cookieobj);
	     
         cookies=driver.manage().getCookies();
	     
	     System.out.println("Size of cookies after adding:"+cookies.size());//26
	    // for(     Cookie   cookie   :cookies)
	   //  {
	    	 
	    	// System.out.println(cookie.getName()+"   :  "+cookie.getValue());
	    	 
	   //  }
	     
	     
	     
	//How to delete specific cookies from the Browser
	     
	     //First method
	     
	  // driver.manage().deleteCookie(cookieobj);
	     
	     //Second method
	     
	driver.manage().deleteCookieNamed("CUR_CODE");
	     
	     
            cookies=driver.manage().getCookies();
	     
	     System.out.println("Size of cookies after deletion :"+cookies.size());//25
	     
	   for(     Cookie   cookie   :cookies)
	     {
	    	 
	    	 System.out.println(cookie.getName()+"   :  "+cookie.getValue());
	    	 
	     }
	     
	     //How to delete all the cookies from the browser
	     
	     
	     driver.manage().deleteAllCookies();
	     
   cookies=driver.manage().getCookies();
	     
	     System.out.println("Size of cookies after Alldeletion:"+cookies.size());//0
	     
	     
	     
	     
	     
	     
	     
	
	

	}

}
